version: '3.8'

services:
  nextjs:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/
            - node_modules/
            - .github/
        - action: rebuild
          path: package.json
  
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
