version: '3.8'

services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/
            - node_modules/
            - .github/
        - action: rebuild
          path: package.json
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      TZ: US/Pacific
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
