apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.secret.secretStoreRef.kind }}
    name: {{ .Values.secret.secretStoreRef.name }}
  target:
    name: {{ .Values.secret.name }}
  data:
{{- range .Values.secret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
{{- end }}
